spring.application.name=02SpringBoot

server.servlet.context-path=/web

server.port=8088

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=hr
spring.datasource.password=12345

mybatis.type-aliases-package=kr.bigdata.web.entity


# 파일 업로드 시 필요한 설정
# 전송받을 파일의 최대 크기를 설정하는 방법
spring.servlet.multipart.max-file-size = 100MB
spring.servlet.multipart.max-request-size = 100MB

# 파일을 저장할 경로 설정

spring.servlet.multipart.location= C:/Users/smhrd/Documents/workspace-spring-tools-for-eclipse-4.30.0.RELEASE/02SpringBoot/src/main/webapp/upload/

