

-- 회원 테이블 생성 -- 
CREATE TABLE MEMBER(
    ID VARCHAR2(100) NOT NULL,
    PW VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(40) NOT NULL,
    PRIMARY KEY (ID)
    );
    
-- 회원정보 조회 -- 
SELECT * FROM MEMBER;

commit;



UPDATE MEMBER SET PW = '12341' WHERE ID='pbk' AND PW = '1234';
UPDATE MEMBER SET PW = '12345' WHERE ID='pbk';
UPDATE MEMBER SET PW = '1234'  WHERE ID='pbk' AND PW = '12341';


CREATE TABLE USER_ (
    ID VARCHAR2(10),
    PW VARCHAR2(10) NOT NULL,
    NAME VARCHAR2(10),
    PRIMARY KEY(NAME),
    UNIQUE(ID)
);

CREATE TABLE LAB_(
    NAME VARCHAR2(10) NOT NULL,
    HARDTIME NUMBER(5,2),
    HARDDATE DATE,
    NORMALTIME NUMBER(5,2),
    NORMALDATE DATE,
    FOREIGN KEY(NAME)
    REFERENCES USER_(NAME)
);
TRUNCATE TABLE USER_;
DROP TABLE USER_ CASCADE CONSTRAINT;
DROP TABLE LAB_ CASCADE CONSTRAINT;
CREATE TABLE MEMBER(
    ID VARCHAR2(100) NOT NULL,
    PW VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(40) NOT NULL,
    PRIMARY KEY (ID)
    );