-- smhrd2
DROP TABLE TB_USER CASCADE CONSTRAINT;
DROP TABLE TB_LAB CASCADE CONSTRAINT;

CREATE TABLE TB_USER (
    ID VARCHAR2(10),
    PW VARCHAR2(10) NOT NULL,
    NAME VARCHAR2(10),
    PRIMARY KEY(NAME),
    UNIQUE(ID)
);

CREATE TABLE TB_LAB(
    NAME VARCHAR2(10) NOT NULL,
    HARD_TM NUMBER(5,2),
    HARD_DT DATE,
    NORMAL_TM NUMBER(5,2),
    NORMAL_DT DATE,
    FOREIGN KEY(NAME)REFERENCES TB_USER(NAME)
    ON DELETE CASCADE
);
COMMIT;
SELECT * FROM TB_USER;
SELECT * FROM TB_LAB;

DELETE FROM TB_USER;

SELECT ROW_NUMBER() OVER (ORDER BY HARD_TM) AS HARD, NAME, HARD_TM, HARD_DT FROM TB_LAB ORDER BY HARD_TM;


SELECT ROW_NUMBER() OVER (ORDER BY HARD_TM) AS HARD, NAME, HARD_TM, HARD_DT FROM TB_LAB WHERE HARD_TM IS NOT NULL;

SELECT ROW_NUMBER() OVER (ORDER BY L.NORMAL_TM) AS NORMAL, L.NAME, L.NORMAL_TM, L.NORMAL_DT
FROM TB_LAB L INNER JOIN TB_USER U
ON L.NAME = U.NAME
WHERE L.NORMAL_TM IS NOT NULL;


COMMIT;
INSERT INTO TB_USER VALUES ('qwe', 'qwe', 'qwe');
INSERT INTO TB_USER VALUES ('zzz', 'zzz', 'qzzz');
INSERT INTO TB_USER VALUES ('zxc', 'zxc', 'zxc');
INSERT INTO TB_USER VALUES ('asd', 'asd', 'asd');
INSERT INTO TB_USER VALUES ('ASD', 'ASD', 'ASD');

INSERT INTO TB_LAB (NAME, HARD_TM, HARD_DT, NORMAL_TM, NORMAL_DT)
VALUES ('동근', '1.11', '25/01/31', '2.22', '25/02/01');
INSERT INTO TB_LAB (NAME, HARD_TM, HARD_DT, NORMAL_TM, NORMAL_DT)
VALUES ('zxc', '44.22', '25/01/31', '55.33', '25/02/01');
INSERT INTO TB_LAB (NAME, HARD_TM, HARD_DT, NORMAL_TM, NORMAL_DT)
VALUES ('asd', '23.11', '25/01/31', '54.22', '25/02/01');
INSERT INTO TB_LAB (NAME, HARD_TM, HARD_DT, NORMAL_TM, NORMAL_DT)
VALUES ('ASD', '44.22', '25/01/31', '55.33', '25/02/01');

INSERT INTO TB_LAB (NAME, HARD_TM, HARD_DT, NORMAL_TM, NORMAL_DT)
VALUES ('ASD', '44.22', TO_DATE('2025/01/31 21:10:22', 'yyyy/mm/dd hh24:mi:ss'), '55.33', '25/02/01');



COMMIT;

-- 수정
--SELECT NAME, HARD_TM, HARD_DT FROM TB_LAB ORDER BY HARD_TM;
--SELECT NAME, NORMAL_TM, NORMAL_DT FROM TB_LAB ORDER BY NORMAL_TM;
